# Generated by Django 6.0.7 on 2026-07-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("USER", "Пользователь"), ("ADMIN", "Администратор")],
                default="USER",
                max_length=10,
                verbose_name="Роль пользователя",
            ),
        ),
    ]
